### ISSUE TITLE
appliance-environment fails to start

### ISSUE THREAD

**Issue by andrewtchin** [neutronbuild/neutron#6]
Missing `ovfenv` binary
Also missing `dcui` binary

When building it seems like these aren't getting built
```
⇒  make ova
Generating dependency set for ovatools/ovfenv/
Cached Go dependency for ovatools/ovfenv/: 
Generating dependency set for ovatools/dcui/
Cached Go dependency for ovatools/dcui/: 
Generating dependency set for ovatools/rpctool/
Cached Go dependency for ovatools/rpctool/: 
fatal: No names found, cannot describe anything.
--------------------------------------------------
starting docker dev build container...
```

Also the build doesn't fail when the file in the manifest isn't present in `bin`

**Comment by ghost** [comment]
1) `fatal: No names found, cannot describe anything.` is a git error. There are no tags on this repo.
2) We don't actually access the manifest yet, so there's no chance for it's absence to cause a problem yet. We should add a check for it later.
3) The `ovfenv`, `dcui` and `rpctool` binaries are built, but they're not copied over to the ova's root fs yet. That's being fixed in #4 which needs my rebase.
